[package]
name = "raster"
version = "0.1.0"
edition = "2024"

[dependencies]
derivative = "2.2.0"
jsonschema = "0.33.0"
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
shellexpand = "3.1.1"
toml = "0.9.5"
regex = "1.12.2"
serial_test = "3.2.0"
